### ISSUE TITLE
ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by J43fura** [ankaboot-source/wikiadviser#651]
```yml
[15:09:42.148] ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
    err: {
      "type": "Error",
      "message": "ON CONFLICT DO UPDATE command cannot affect row a second time",
      "stack":
          Error: ON CONFLICT DO UPDATE command cannot affect row a second time
              at upsertChanges (/app/helpers/supabaseHelper.js:44:15)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async MediawikiClient.updateChanges (/app/services/mediawikiAPI/MediawikiClient.js:186:9)
              at async updateArticleChanges (/app/controllers/article.controller.js:129:9)
    }
```

**Comment by J43fura** [comment]
can't repro
